name: C++ CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake ninja-build g++ libboost-all-dev libssl-dev libspdlog-dev nlohmann-json3-dev libgtest-dev libprotobuf-dev protobuf-compiler

      - name: Make project & tests
        run: |
          mkdir build
          cd build
          cmake -G "Ninja" ..
          ninja -j$(nproc)

      - name: Run tests
        run: ctest