name: C++ CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ libboost-asio-dev libssl-dev libspdlog-dev nlohmann-json3-dev libgtest-dev

      - name: Make project & tests
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run tests
        run: ./build/test
